specVersion: 1.0.0
name: algorand-randgallery
version: 1.0.0
runner:
  node:
    name: "@subql/node-algorand"
    version: ">=1.0.0"
  query:
    name: "@subql/query"
    version: "*"
description: >-
  This project is a quick start guide for developing your Algorand SubQuery project, it indexes RandGallery's transactions.
repository: "https://github.com/jamesbayly/algorand-planet-watch"
schema:
  file: ./schema.graphql
network:
  chainId: "wGHE2Pwdvd7S12BL5FaOP20EGYesN73ktiC1qzkkit8="
  # Must be a non-pruned archive node
  endpoint: "https://algoindexer.algoexplorerapi.io"
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: https://api.subquery.network/sq/subquery/Algorand-Dictionary
dataSources:
  - kind: algorand/Runtime
    startBlock: 14439171 # Block that Rand account received first transaction. This is used to speed up indexing. 
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransaction
          kind: algorand/TransactionHandler
          filter:
            # payments to the RandGallery Address for the Algo asset
            txType: pay
            assetId: 0
            receiver: "RANDGVRRYGVKI3WSDG6OGTZQ7MHDLIN5RYKJBABL46K5RQVHUFV3NY5DUE"
